### ISSUE TITLE
Dockerfiles for x86 and aarch64 are very similar

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/rust-vmm-container#3]
Can we have a "basic" Docker file (I think that might be a layer) that Dockerfile.x86_64 and Dockerfile.aarch64 can inherit from so we don't have so many duplicated commands in both files? Then depending on the architecture we can have other specific commands on top of the common layer.

**Comment by MrXinWang** [comment]
Hi @andreeaflorescu ! I have created a [PR#20](https://github.com/rust-vmm/rust-vmm-container/pull/20) to possibly address this issue. Please review

**Comment by andreeaflorescu** [comment]
Fixed by PR #20
