### ISSUE TITLE
Create script for publishing new container versions

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/rust-vmm-container#44]
We now have manual steps that we need to do for publishing a new container versions. These are only available for the Linux container. We should create a script that does:
- docker build
- docker tag (to find the version can we somehow read the latest available version from docker, and just incremented by one?)
- docker publish

We should make sure that the windows & linux containers have the same versions.

Once these scripts are available, we can setup a CI such that the builds happen on every commit that changes the docker files.

**Comment by FedericoPonzi** [comment]
Hey, can I have this?

**Comment by andreeaflorescu** [comment]
Thanks @FedericoPonzi for picking this up!
