### ISSUE TITLE
Cargo audit does not seem to be installed on arm anymore

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/rust-vmm-container#79]
This makes the cargo audit test fail when running on an arm platform.
Failure example: https://buildkite.com/rust-vmm/kvm-bindings-ci/builds/139#01874646-cd0e-4772-b671-a7644ccc2522

**Comment by roypat** [comment]
The container also seems to be missing the critcmp tool on aarch64 that’s used in the benchmark tests (e.g. see [here](https://buildkite.com/rust-vmm/linux-loader-ci/builds/577#01873e9c-73bf-43ea-b217-2a12ca57533b) for a CI failure related to that on the linux loader dependabot PR)

**Comment by stefano-garzarella** [comment]
@andreeaflorescu Looks like `cargo install cargo-kcov critcmp cargo-audit cargo-fuzz` is killed while building the `arm64` image: https://github.com/rust-vmm/rust-vmm-container/actions/runs/4596111102/jobs/8117163969#step:7:2665

Could it be the `OOM Killer`? Do we know how much memory the workers have?
I don't know whether splitting calls to `cargo install` into multiple calls would help or not.

How can we test without publishing new versions?
